.\" $Id: web100_perror.3,v 1.3 2002/02/27 04:11:44 engelhar Exp $
.TH web100_perror 3 "26 February 2002" "Web100 Userland" "Web100"
.SH NAME
web100_perror \- print a web100 error message in the style of \fBperror\fR(3).
.SH SYNOPSIS
.B #include <web100/web100.h>
.PP
.BI "void web100_perror(const char* " s ");"
.SH DESCRIPTION
The \fBweb100_perror\fR function prints a message on the standard error
output describing the last error encountered during a call to a
\fIlibweb100\fR function.  The argument string \fIs\fR is printed first,
then a colon and a blank, then the message and a new-line.  The error
number is taken from the external variable \fIweb100_errno\fR, which is
set by \fIlibweb100\fR functions upon failure.
.SH SEE ALSO
.BR web100_strerror (3),
.BR libweb100 (3)
