.\" $Id: web100_attach.3,v 1.7 2002/12/12 19:54:23 engelhar Exp $
.TH WEB100_ATTACH 3 "12 December 2002" "Web100 Userland" "Web100"
.SH NAME
web100_attach, web100_detach \- attach to and detach from a Web100 data
source (SNMP terminology)
.SH SYNOPSIS
.B #include <web100/web100.h>
.PP
.nf
.BI "web100_agent* web100_attach(int " type ", void* " data ");"
.BI "void          web100_detach(web100_agent* " agent ");"
.fi
.SH DESCRIPTION
The \fBweb100_attach()\fR function attaches to a Web100 data source.
Most commonly, the data source is the local machine, but future versions
of Web100 may support remote machines as a data source.  It is typically
the first function called by users of \fIlibweb100\fR, and it returns a
\fIweb100_agent\fR which may be used by subsequent functions.
.PP
The argument \fImethod\fR denotes how the data will be gathered.  Each
\fImethod\fR has its own requirements for the contents of \fIdata\fR.
These requirements are explained below.
.PP
Choose \fImethod\fR from the following:
.TP
\fBWEB100_AGENT_TYPE_LOCAL\fR
The Web100 data source is the local machine, as it is running a
Web100-enabled kernel.  \fIdata\fR should be NULL.
.PP
\fBweb100_detach()\fR closes and deallocates a previously obtained
\fIagent\fR.
.SH RETURN VALUES
\fBweb100_attach()\fR returns an initialized \fIweb100_agent\fR that may
be used by subsequent functions, or \fBNULL\fR if it fails for any
reason.
.PP
\fBweb100_detach()\fR returns no value.
.SH SEE ALSO
.BR libweb100 (3)
