.\" $Id: web100_snap_accessors.3,v 1.1 2002/12/12 19:54:26 engelhar Exp $
.TH WEB100_SNAP 3 "12 December 2002" "Web100 Userland" "Web100"
.SH NAME
web100_get_snap_group, web100_get_snap_group_name \- get values from the
Web100 snapshot opaque structure
.SH SYNOPSIS
.B #include <web100/web100.h>
.PP
.nf
.BI "web100_group* web100_get_snap_group(web100_snapshot* " snap ");"
.BI "const char*   web100_get_snap_group_name(web100_snapshot* " snap ");"
.fi
.SH DESCRIPTION
As the \fIweb100_snapshot\fR structure is opaque, these functions exist
to fetch values from it without exposing its structure.
.SH RETURN VALUES
\fBweb100_get_snap_group()\fR returns the group associated with the
snapshot.
.PP
\fBweb100_get_snap_group_name()\fR returns the name of the group
associated with the snapshot.
.SH SEE ALSO
.BR libweb100 (3)
