.\" $Id: web100_strerror.3,v 1.2 2002/02/27 03:39:51 engelhar Exp $
.TH web100_strerror 3 "26 February 2002" "Web100 Userland" "Web100"
.SH NAME
web100_strerror \- return string describing error code in the style of
\fBstrerror\fR(3)
.SH SYNOPSIS
.B #include <web100/web100.h>
.PP
.BI "const char* web100_strerror(int " errnum ");"
.SH DESCRIPTION
The \fBweb100_strerror\fR function returns a string describing the error
code passed in the argument \fIerrnum\fR.  This is the same string which
is printed after the colon in \fBweb100_perror\fR.  This function is
usually used with \fIweb100_errno\fR as its argument.
.SH RETURN VALUES
The \fBweb100_strerror\fR function returns the appropriate description
string, or "unknown error" if the error code is unknown.
.SH SEE ALSO
.BR web100_perror (3),
.BR libweb100 (3)
