.\" $Id: web100_log_accessors.3,v 1.1 2002/12/12 19:54:25 engelhar Exp $
.TH WEB100_LOG 3 "12 December 2002" "Web100 Userland" "Web100"
.SH NAME
web100_get_log_agent, web100_get_log_group, web100_get_log_connection,
web100_get_log_time \- get values from the Web100 log opaque structure
.SH SYNOPSIS
.B #include <web100/web100.h>
.PP
.nf
.BI "web100_agent*      web100_get_log_agent(web100_log* " log ");"
.BI "web100_group*      web100_get_log_group(web100_log* " log ");"
.BI "web100_connection* web100_get_log_connection(web100_log* " log ");"
.BI "time_t             web100_get_log_time(web100_log* " log ");"
.fi
.SH DESCRIPTION
As the \fIweb100_log\fR structure is opaque, these functions exist to
fetch values from it without exposing its structure.
.SH RETURN VALUES
\fBweb100_get_log_agent()\fR returns the agent associated with the log.
.PP
\fBweb100_get_log_group()\fR returns the group associated with the log.
.PP
\fBweb100_get_log_connection()\fR returns the connection associated with
the log.
.PP
\fBweb100_get_log_time()\fR returns the time the log was taken.
.SH SEE ALSO
.BR libweb100 (3)
