.\" $Id: web100_agent_find_var_and_group.3,v 1.3 2002/12/12 19:54:23 engelhar Exp $
.TH WEB100_AGENT 3 "28 February 2002" "Web100 Userland" "Web100"
.SH NAME
web100_agent_find_var_and_group \- given the name of a variable, return the appropriate web100_var and web100_group
.SH SYNOPSIS
.B #include <web100/web100.h>
.PP
.nf
.BI "int web100_agent_find_var_and_group(web100_agent* " agent ", const char* " varname ", web100_group** " group ", web100_var** " var ");"
.fi
.SH DESCRIPTION
\fBweb100_agent_find_var_and_group()\fR finds the Web100 variable with
name \fIvarname\fR in \fIagent\fR and returns its \fIgroup\fR and
\fIvar\fR values.
.SH RETURN VALUES
\fBweb100_agent_find_var_and_group()\fR returns \fBWEB100_ERR_SUCCESS\fR
if the variable is found or an error code otherwise.
.SH EXAMPLE USE
.nf
/* Warning: no errorhandling below... */
web100_agent* agent;
web100_group* group;
web100_var* var;

agent = web100_attach(WEB100_AGENT_TYPE_LOCAL, NULL);
web100_agent_find_var_and_group(agent, "RemotePort", &group, &var);
.fi
.SH SEE ALSO
.BR web100_group_find (3),
.BR web100_var_find (3),
.BR libweb100 (3)
