#!/bin/sh

prefix="/usr"
exec_prefix="/usr"
cflags="-I/usr/include"
libs="-L/usr/lib/x86_64-linux-gnu -lweb100"
version="@VERSION@"

usage()
{
  cat <<EOF
Usage: web100-config [OPTIONS]
Options:
        [--prefix]
        [--exec-prefix]
        [--version]
        [--libs]
        [--cflags]
EOF
  exit $1
}

if test $# -eq 0; then
  usage 1 1>&2
fi

while test $# -gt 0; do
  case $1 in
    --prefix)
      echo ${prefix}
      ;;
    --exec-prefix)
      echo ${exec_prefix}
      ;;
    --version)
      echo ${version}
      ;;
    --cflags)
      echo ${cflags}
      ;;
    --libs)
      echo ${libs}
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done
