.\" $Id: deltavar.1,v 1.2 2002/09/03 17:36:31 engelhar Exp $
.TH deltavar 1 "26 February 2002" "Web100 Userland" "Web100"
.SH NAME
deltavar \- monitor a single Web100 variable continuously, printing out how
much it changes each second.
.SH SYNOPSIS
.B deltavar
.I connection_id
.I var_name
.SH DESCRIPTION
\fBdeltavar\fR runs in an infinite loop, creating a snapshot of the
current value of the Web100 variable \fIvar_name\fR from the connection
\fIconnection_id\fR once every second and printing out the difference
from the previous value.
.SH SEE ALSO
.BR gutil (1),
.BR readvar (1),
.BR readall (1),
.BR writevar (1),
.BR web100 (7)
