.\" $Id: readall.1,v 1.2 2002/09/03 17:36:31 engelhar Exp $
.TH readall 1 "26 February 2002" "Web100 Userland" "Web100"
.SH NAME
readall \- read the current value of all Web100 variables from all connections.
.SH SYNOPSIS
.B readall
.SH DESCRIPTION
\fBreadall\fR iterates over all connections, grouping and printing out each
Web100 variable from each one.
.SH SEE ALSO
.BR gutil (1),
.BR readvar (1),
.BR writevar (1),
.BR deltavar (1),
.BR web100 (7)
